Repository Project-PetCare/petcare-app, pull requests merged in 2024-04, with the labels that each got.

#56 Sign-in with Google
  app/src/main/java/fi/project/petcare/ui/composables/GoogleSignInButton.kt
  app/src/main/java/fi/project/petcare/ui/screens/WelcomeScreen.kt
  app/src/main/java/fi/project/petcare/viewmodel/AuthViewModel.kt
Labels: bug

#57 Petprofilescreen
  app/src/main/java/fi/project/petcare/PetCareApp.kt
  app/src/main/java/fi/project/petcare/ui/screens/HomeScreen.kt
  app/src/main/java/fi/project/petcare/ui/screens/ProfileScreen.kt
  app/src/main/res/drawable/arrow_icon.png
  app/src/main/res/drawable/labtest.jpg
  app/src/main/res/drawable/medical_record_icon.png
  app/src/main/res/drawable/medical_record_icon1.jpg
  app/src/main/res/drawable/medical_record_icon2.png
  app/src/main/res/drawable/pet_icon_2.jpg
  app/src/main/res/drawable/prescription.jpg
  app/src/main/res/drawable/setting_icon.png
Labels: enhancement

#50 Feat/dashboard
  app/src/main/java/fi/project/petcare/ui/composables/Dashboard.kt
  app/src/main/java/fi/project/petcare/ui/composables/PetCareBottomBar.kt
  app/src/main/java/fi/project/petcare/ui/composables/PetCareTopBar.kt
  app/src/main/java/fi/project/petcare/ui/nav/AppNavigation.kt
  app/src/main/java/fi/project/petcare/ui/nav/PetCareDestinations.kt
  app/src/main/java/fi/project/petcare/ui/screens/HomeScreen.kt
  app/src/main/java/fi/project/petcare/ui/screens/PetListScreen.kt
  app/src/main/java/fi/project/petcare/ui/screens/ProfileScreen.kt
  app/src/main/java/fi/project/petcare/ui/screens/WelcomeScreen.kt
  app/src/main/java/fi/project/petcare/ui/theme/Color.kt
  app/src/main/res/mipmap-xhdpi/ic_cat_welcome.png
Labels: enhancement

#64 build: Update Java version to 17
  app/build.gradle.kts
Labels: dependencies

#76 Fetch and display pet's information
  app/build.gradle.kts
  app/src/main/java/fi/project/petcare/PetCareApp.kt
  app/src/main/java/fi/project/petcare/model/data/Pet.kt
  app/src/main/java/fi/project/petcare/model/data/SupabaseClient.kt
  app/src/main/java/fi/project/petcare/model/repository/PetRepository.kt
  app/src/main/java/fi/project/petcare/ui/composables/LoadingIndicator.kt
  app/src/main/java/fi/project/petcare/ui/nav/AppNavigation.kt
  app/src/main/java/fi/project/petcare/ui/screens/PetListScreen.kt
  app/src/main/java/fi/project/petcare/ui/screens/WelcomeScreen.kt
  app/src/main/java/fi/project/petcare/viewmodel/AuthViewModel.kt
  app/src/main/java/fi/project/petcare/viewmodel/PetCareViewModel.kt
  app/src/main/java/fi/project/petcare/viewmodel/PetViewModel.kt
  app/src/main/res/drawable/ic_cat_welcome.webp
  app/src/main/res/drawable/ic_dog_loading.xml
  gradle/libs.versions.toml
Labels: enhancement

#77 Redesign list of pets screen
  app/src/main/java/fi/project/petcare/ui/composables/LoadingIndicator.kt
  app/src/main/java/fi/project/petcare/ui/screens/HomeScreen.kt
  app/src/main/java/fi/project/petcare/ui/screens/PetListScreen.kt
Labels: enhancement
